### ISSUE TITLE
Wish: shading without density lines?

### ISSUE THREAD

**Issue by ugroempi** [kwstat/corrgram#10]
Hi Kevin,

I dearly miss a possibility to remove the density lines for shading; I find them quite distracting and simply cannot see any reason for showing them. Is there any chance for an option to function `panel.shade` that allows density shading to be removed? I can of course do my own function, but I think that this would just be better without the lines for (almost) everybody ... 

Best, Ulrike

**Comment by kwstat** [comment]
Added `panel.fill` function that mimics `panel.shade` without diagonal lines.

[`[e0c4e5049200aec620c8c8ea3cd941b75dc58b12](url)`](https://github.com/kwstat/corrgram/commit/e0c4e5049200aec620c8c8ea3cd941b75dc58b12)
