### ISSUE TITLE
Misleading text sizes for panel.cor

### ISSUE THREAD

**Issue by ugroempi** [kwstat/corrgram#11]
Hi Kevin,
currently, for autosizing of text, negative numbers have a smaller `cex` than positive ones in `panel.cor`, which gives a misleading visual impression especially when comparing e.g. -0.89 to 0.23. I know too little about how panel functions operate to offer a professional fix; I have made a workaround for myself that calculates the string width from formatted forced negative values.
Best, Ulrike

**Comment by kwstat** [comment]
Good observation.  `panel.cor` now uses absolute value of correlation to auto-size text.
[https://github.com/kwstat/corrgram/commit/e662ab484cc90c39bb63bf6606b20f0013e17a65](https://github.com/kwstat/corrgram/commit/e662ab484cc90c39bb63bf6606b20f0013e17a65)
