### ISSUE TITLE
Pearson correlations in panel.conf, even though Spearman requested

### ISSUE THREAD

**Issue by heinonmatti** [kwstat/corrgram#13]
I noticed the following thing (and sorry for the lack of a reproducible example, this is my first GitHub issue):

- Taking Pearson correlations,  the correlations match the pies (see e.g. correlation between tiredness and clarity).

![image](https://user-images.githubusercontent.com/16374562/36093170-81ef5b6a-0ff2-11e8-9ded-bcf3947cf478.png)

- Taking Spearman correlations, the upper panel still indicates Pearson correlations, though pies in the lower panel show the Spearman correlations:

![image](https://user-images.githubusercontent.com/16374562/36091598-e4aed74a-0fec-11e8-9496-56024a4b1a1e.png)

This seems to happen with all my data. Corrgram version is 1.12.

**Comment by kwstat** [comment]
`panel.conf` now only allows `cor.method="pearson"` (which is the default.) Fix issue #13. https://github.com/kwstat/corrgram/commit/fc8640d98f8f973343fcd1e4172efed6e41048bb
