### ISSUE TITLE
Error: object ‘cividis’ is not exported by 'namespace:viridisLite'

### ISSUE THREAD

**Issue by Friskfisk** [kwstat/corrgram#14]
I've reinstalled both viridis an viridisLite, and still get same error.  Same error with: library(viridis), so looks like it could be a viridis bug rather than a corrgram?

**Comment by kwstat** [comment]
I doubt this is a corrgram bug. Seems to work for me.

R> library(viridis)
Loading required package: viridisLite
R> cividis
function (n, alpha = 1, begin = 0, end = 1, direction = 1) 
{
    viridis(n, alpha, begin, end, direction, option = "cividis")
}
<environment: namespace:viridisLite>

Can you provide a reproducible example? Make sure you have updated all packages...cividis was added to viridis fairly recently I think.

**Comment by Friskfisk** [comment]
I just re-downloaded all related packages, and I'm running R version 3.4.3:

> library(viridisLite)
> library(viridis)
Error: package or namespace load failed for ‘viridis’:
 object ‘cividis’ is not exported by 'namespace:viridisLite'
> library(corrgram)
Error: package or namespace load failed for ‘corrgram’:
 object ‘cividis’ is not exported by 'namespace:viridisLite'

Thanks for the support on this,

Cooper

**Comment by kwstat** [comment]
Strange.  I'm also on R 3.4.3 and the following steps worked fine for me and drew the corrgram.
```
library(viridisLite)
library(viridis)
library(corrgram)
corrgram(iris, col=viridis)
```
Since your error message happens *before* you load corrgram, the error is not related to corrgram.  You might need to search for the error message and try some other ideas, for example:

https://stackoverflow.com/questions/48962946/error-package-or-namespace-load-failed-for-arulesviz-object-cividis-is-not

Good luck.

**Comment by Friskfisk** [comment]
but, but, but, viridis package is not required for corrgram.  Upstream
changes are causing downstream issues, both in corrgram and in viridis.
Yes I've looked through the forum stuff.

**Comment by kwstat** [comment]
I totally agree that _you_ are having a problem.  But the error happens before before you load corrgram and I cannot reproduce the error.  I can't fix something that's not broken.  I'm sorry.  I know it's frustrating.  I've had to deal with this kind of stuff a time or two (like two days ago) and it can be very difficult to fix.
