### ISSUE TITLE
Not loading the package to namespace: Object [panel.conf/panel.pie etc.] not found

### ISSUE THREAD

**Issue by heinonmatti** [kwstat/corrgram#15]
Hi,

Apologies in advance if I'm doing something stupid here, but I've been getting a weird error for a while. 

```
var1 <- rnorm(n = 700, mean = 100, sd = 20)
var2 <- rnorm(n = 700, mean = 100, sd = 20)
var3 <- rnorm(n = 700, mean = 100, sd = 20)
var4 <- rnorm(n = 700, mean = 100, sd = 20)

corrgram::corrgram(data.frame(var1, var2, var3, var4), upper.panel = panel.conf)
```

This gives me: 

> Error in corrgram::corrgram(data.frame(var1, var2, var3, var4), upper.panel = panel.conf) : 
>   object 'panel.conf' not found

The documentation speaks about a "tall" format data frame, but making the df long doesn't help

```
data.frame(var1, var2, var3, var4) %>% 
  gather(variable, value, var1:var4) %>% 
  corrgram::corrgram(., upper.panel = panel.conf)
```

Many thanks for your help!

R 3.4.3, corrgram 1.12

**Comment by heinonmatti** [comment]
Ok, mystically figured it out just after pressing send: need to call the package with library(). 

I have a very long supplement file and run into maxed DLLs, thus would like to call functions with package::function. Is it possible to use corrgram like this?

**Comment by kwstat** [comment]
You can actually use the package without using ``library(corrgram)``.  In order to do so, you have to preface ALL calls to functions (including the panel functions)in the package with ``corrgram::`` like this:
``corrgram::corrgram(data.frame(var1, var2, var3, var4), upper.panel = corrgram::panel.conf)``

**Comment by heinonmatti** [comment]
Very good, many thanks!!
