### ISSUE TITLE
Label ordering mismatch issue when using both "order=T" and "labels" arguments

### ISSUE THREAD

**Issue by matthieu-bruneaux** [kwstat/corrgram#4]
Hi,

I was recently confounded at some unexpected differences in the correlation estimates for a given pair of variables shown in corrgram plots for the same input data, depending on whether I used or not "order = T" and provided some labels to replace the column names of the input data frame.

After some time I realised it was just a matter of the labels not being ordered on the plot when I provide them myself with the "labels" argument.

Here is an example:

```
corrgram(mtcars, lower.panel = panel.conf) # Correlation between mpg and hp is -0.78
corrgram(mtcars, lower.panel = panel.conf, order = T) # Still ok

# Now if I want to replace the label "hp" by "horse\npower"
myLabels = names(mtcars)
myLabels[myLabels == "hp"] = "horse\npower"

corrgram(mtcars, lower.panel = panel.conf, labels = myLabels) # Still ok
corrgram(mtcars, lower.panel = panel.conf, labels = myLabels, order = T) # Not ok anymore
```

In the last plot the upper and lower panels are correctly reorder, but the labels I provided to the function are not reordered, resulting in a mismatch between the labels and the actual rows/columns.

I guess this could be either fixed in the corrgram function code so that labels are correctly ordered, or it could be said explicitly in the help for the corrgram function that if the user provides labels they will not be reordered.

I can try to modify the function to reorder provided labels and submit a patch if you think this is the best way?

Thank you for this very nice package!

**Comment by kwstat** [comment]
Good catch. I've added your examples to the tests folder.

**Comment by kwstat** [comment]
Package source on CRAN now.
