### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by IrinaMax** [kwstat/corrgram#6]
Could not installing from CRAN in R Studio, but easy installed when I download it locally.

**Comment by kwstat** [comment]
Thanks. When you file a bug report, please try to be as specific as you can.  In this case that might include: What version of R, what platform, what repository mirror are you using, did you try any other mirrors, were you able to install any other packages besides corrgram, copy and paste the console error message into the bug report. 

I suspect that you had a problem with the configuration of your repository mirror or that the mirror was down.  Many other people (and myself) have no problems installing (see below).  I'm going to close this thread, but if you continue to have problems, try answering the questions above.

```
R> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch    
   
R> install.packages("corrgram")
Installing package into ‘C:/kw/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/corrgram_1.10.zip'
Content type 'application/zip' length 792327 bytes (773 KB)
downloaded 773 KB

package ‘corrgram’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Temp\RtmpCSwpyj\downloaded_packages
```
