### ISSUE TITLE
Misleading vignette title

### ISSUE THREAD

**Issue by ugroempi** [kwstat/corrgram#8]
Hi Kevin,

the vignette title "cov2cor() may not give a valid correlation matrix" is a bit misleading in that it seems to blame `cov2cor` for some wrong-doing. If given a proper covariance matrix, `cov2cor` *does* give a valid correlation matrix. The matrix you use in the vignette has a negative eigen value and can therefore not have arisen as a covariance matrix:

`> eigen(vv)$values`
`[1]  4.808047e+02  9.965048e+01  4.595154e+01  2.657509e+01`
`[5]  8.304329e+00  6.685001e-04 -8.147905e-04`

If the negative eigen value is eliminated, the result of `cov2cor` becomes a proper correlation matrix:
`P <- eigen(vv)$vectors`
`cov2cor(P[,-7]%*%diag(eigen(vv)$values[1:6])%*%t(P[,-7]))`

Best, Ulrike

**Comment by kwstat** [comment]
Good point. Wasn't my intention to blame...just to suggest a way to "fix" an improper correlation matrix.  I'll tweak the text and change the title to:
"Finding the nearest proper correlation matrix"

I suspect the example matrix arose from cov(..., use="pairwise").

Thanks,
Kevin
